version: '3.4'

services:
  productdb:
    container_name: productdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=productdb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_product:/var/lib/postgresql/data/ 
  product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=productdb;Port=5432;Database=productdb;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - productdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
